Api-Login and Profile
shahkushal38/SyncWithPride-BackEnd pull request #1
Opened 2024-02-25 09:13 UTC by Krutikaa04

created two APIs -->
POST login api
GET profile api

database collection named users
sample data included

jwt token generated.

2024-02-28 13:01 UTC, shahkushal38 requested changes
LGTM! Have given suggestions to make the code clean and better to understand

2024-02-28 13:01 UTC, shahkushal38 commented on app.js
> +require("dotenv").config();
This line should come after const jwt line.... ie line 6

2024-02-28 13:01 UTC, shahkushal38 commented on app.js
> +    return res.status(422).json({error:"fill field properly"});
Why response status as 422? Isn't it be 400 

And check for all other cases too please

2024-02-28 13:01 UTC, shahkushal38 commented on app.js
> +    token = jwt.sign({_id: this._id, email: this.email}, process.env.SECRET_TOKEN, {expiresIn: "30s"});
This should not be 30s it should be atleast 24hrs

2024-02-28 13:01 UTC, shahkushal38 commented on model/maindb.js
> +// function userInsert(){
remove this unwanted code if not needed

2024-02-28 13:01 UTC, shahkushal38 commented on model/schema1.js
> +const mongoose = require("mongoose");
Please rename the file to userSchema.js to make it understandable

2024-02-29 05:35 UTC, Krutikaa04 commented
Resolved the following : 
1.  status codes changed accordingly
2.  jwt expiry time changed from 30s to 24h
3.  removed unwanted code
4. renamed the file 
5. the database url and the port are now hidden

2024-02-29 10:04 UTC, shahkushal38 approved these changes
LGTM! PR Approved

2024-02-29 10:46 UTC, EshantBagwe approved these changes

2024-02-29 11:01 UTC, shahkushal38 approved these changes
approved

2024-02-29 11:03 UTC, merged