POST booking api and GET userlist api
shahkushal38/SyncWithPride-BackEnd pull request #2
Opened 2024-02-29 15:30 UTC by Krutikaa04

A new bookingSchema was created under model.
POST booking api and GET userlist api are created.
A collection is created under database named bookings.

2024-03-03 12:59 UTC, Krutikaa04 commented
made some more changes as follows : 
made a POST registration api
changed the login api from POST to GET
added the autheticate credentials feature in login api

2024-03-04 05:21 UTC, shahkushal38 requested changes
Reviewed with comments

2024-03-04 05:21 UTC, shahkushal38 commented on app.js
> +        token: token,
Along with token also please send the user email and username

2024-03-04 05:21 UTC, shahkushal38 commented on app.js
> +   await Users.findOne({ email: email}).then((userExist)=>{
Find by email and username both

2024-03-04 05:21 UTC, shahkushal38 commented on app.js
> +      const bookings = new Booking({username, email, branch, date, deskNo});
Here you are not handling the case that if the desk is already booked for that particular date and time, then you should give and error response that desk is already booked

2024-03-04 05:21 UTC, shahkushal38 commented on model/bookingSchema.js
> +    },
Add time i.e. the slot in that particular date along with Date for booking

2024-03-04 05:21 UTC, shahkushal38 commented on app.js
> +      const bookings = new Booking({username, email, branch, date, deskNo});
Date and slot time needs to be saved in booking table

2024-03-09 09:42 UTC, shahkushal38 approved these changes
approved

2024-03-09 09:52 UTC, Abhiru0116 approved these changes
approved

2024-03-09 10:04 UTC, Abhiru0116 approved these changes
approved!

2024-03-09 10:04 UTC, merged